#define CF_EnemyMask	0x1
#define CF_Listable	0x2
#define CF_Bombable	0x4
#define CF_Untouchable	0x8
#define CT_Mask		0x7F
#define CT_Explode	0x80	//map only
#define CT_Detail	0x80	//panel only
#define cellCount	109

enum cellTypeEnum{
	CT_Null=-1,
	CT_CellTag,
	CT_BraveMan,
	CT_Thief,
	CT_ThiefTalked,
	CT_Princess,
	CT_PrincessTalked,
	CT_OldMan,
	CT_OldManTalked,
	CT_Merchant,
	CT_MerchantBought,
	CT_MerchantTalked,
	CT_AltarW,
	CT_Altar,
	CT_AltarE,
	CT_UpStair,
	CT_DownStair,
	CT_Wall,
	CT_FakeWall,
	CT_FakeRoad,
	CT_RedDoor,
	CT_BlueDoor,
	CT_YellowDoor,
	CT_SteelGate,
	CT_IronGate,
	CT_Lava,
	CT_Star,
	CT_GreenSlime,
	CT_RedSlime,
	CT_Bat,
	CT_Priest,
	CT_SkeletonC,
	CT_SkeletonB,
	CT_GateKeeperC,
	CT_SkeletonA,
	CT_BigSlime,
	CT_BigBat,
	CT_Zombie,
	CT_SuperionPriest,
	CT_Rock,
	CT_ZombieKnight,
	CT_Vampire,
	CT_SlimeMan,
	CT_GhostSoldier,
	CT_Soldier,
	CT_GateKeeperB,
	CT_Swordsman,
	CT_Knight,
	CT_GoldenKnight,
	CT_SlimeLord,
	CT_VampireBat,
	CT_MagicianB,
	CT_MagicianA,
	CT_MagicSergeant,
	CT_DarkKnight,
	CT_GateKeeperA,
	CT_GiantOctopusNW,
	CT_GiantOctopusN,
	CT_GiantOctopusNE,
	CT_GiantOctopusW,
	CT_GiantOctopusC,
	CT_GiantOctopusE,
	CT_GiantOctopusSW,
	CT_GiantOctopusS,
	CT_GiantOctopusSE,
	CT_DragonNW,
	CT_DragonN,
	CT_DragonNE,
	CT_DragonW,
	CT_DragonC,
	CT_DragonE,
	CT_DragonSW,
	CT_DragonS,
	CT_DragonSE,
	CT_GreatMagicMaster,
	CT_Zeno49A,
	CT_Zeno49B,
	CT_Zeno50,
	CT_RedKey,
	CT_BlueKey,
	CT_YellowKey,
	CT_RedElixir,
	CT_BlueElixir,
	CT_RedCrystal,
	CT_BlueCrystal,
	CT_IronSword,
	CT_SilverSword,
	CT_SwordOfKnight,
	CT_HolySword,
	CT_SacredSword,
	CT_IronShield,
	CT_SilverShield,
	CT_ShieldOfKnight,
	CT_HolyShield,
	CT_SacredShield,
	CT_OrbOfHero,
	CT_OrbOfWisdom,
	CT_OrbOfFlying,
	CT_Cross,
	CT_MagicElixir,
	CT_MagicMattock,
	CT_DestructibleBall,
	CT_WarpStaff,
	CT_WingsToFlyUp,
	CT_WingsToFlyDown,
	CT_DragonSlayer,
	CT_SnowCrystal,
	CT_MagicKey,
	CT_SuperMagicMattock,
	CT_LuckyGold,
};

struct cell_t{
	int image;
	int imageP;
	int life;
	int attack;
	int defend;
	int gold;
	int flag;
	const wchar_t *name;
};

const struct cell_t cell[cellCount]={
	{ICO_CellTag,		ICO_Null,		0,	0,	0,	0,	0x0,	NULL			},
	{ICO_BraveMan,		ICO_BraveMan,		0,	0,	0,	0,	0x0,	szCell_BraveMan		},
	{ICO_Thief,		ICO_Thief,		0,	0,	0,	0,	0x0,	szCell_Thief		},
	{ICO_Thief,		ICO_Thief,		0,	0,	0,	0,	0x0,	szCell_Thief		},
	{ICO_Princess,		ICO_Princess,		0,	0,	0,	0,	0x0,	szCell_Princess		},
	{ICO_Princess,		ICO_Princess,		0,	0,	0,	0,	0x0,	szCell_Princess		},
	{ICO_OldMan,		ICO_OldMan,		0,	0,	0,	0,	0x0,	szCell_OldMan		},
	{ICO_OldMan,		ICO_OldMan,		0,	0,	0,	0,	0x0,	szCell_OldMan		},
	{ICO_Merchant,		ICO_Merchant,		0,	0,	0,	0,	0x0,	szCell_Merchant		},
	{ICO_Merchant,		ICO_Merchant,		0,	0,	0,	0,	0x0,	szCell_Merchant		},
	{ICO_Merchant,		ICO_Merchant,		0,	0,	0,	0,	0x0,	szCell_Merchant		},
	{ICO_AltarW,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_AltarC,		ICO_AltarC,		0,	0,	0,	0,	0x0,	szCell_Altar		},
	{ICO_AltarE,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_UpStair,		ICO_UpStair,		0,	0,	0,	0,	0x0,	szCell_Stair		},
	{ICO_DownStair,		ICO_DownStair,		0,	0,	0,	0,	0x0,	szCell_Stair		},
	{ICO_Wall,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_FakeWall,		ICO_FakeWall,		0,	0,	0,	0,	0x0,	szCell_FakeWall		},
	{ICO_FakeRoad,		ICO_FakeRoad,		0,	0,	0,	0,	0x0,	szCell_FakeRoad		},
	{ICO_RedDoor,		ICO_RedDoor,		0,	0,	0,	0,	0x0,	szCell_RedDoor		},
	{ICO_BlueDoor,		ICO_BlueDoor,		0,	0,	0,	0,	0x0,	szCell_BlueDoor		},
	{ICO_YellowDoor,	ICO_YellowDoor,		0,	0,	0,	0,	0x0,	szCell_YellowDoor	},
	{ICO_SteelGate,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_IronGate,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_Lava,		ICO_Lava,		0,	0,	0,	0,	0x0,	szCell_Lava		},
	{ICO_Star,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_GreenSlime,	ICO_GreenSlime,		35,	18,	1,	1,	0x7,	szCell_GreenSlime	},
	{ICO_RedSlime,		ICO_RedSlime,		45,	20,	2,	2,	0x7,	szCell_RedSlime		},
	{ICO_Bat,		ICO_Bat,		35,	38,	3,	3,	0x7,	szCell_Bat		},
	{ICO_Priest,		ICO_Priest,		60,	32,	8,	5,	0x7,	szCell_Priest		},
	{ICO_SkeletonC,		ICO_SkeletonC,		50,	42,	6,	6,	0x7,	szCell_SkeletonC	},
	{ICO_SkeletonB,		ICO_SkeletonB,		55,	52,	12,	8,	0x7,	szCell_SkeletonB	},
	{ICO_GateKeeperC,	ICO_GateKeeperC,	50,	48,	22,	12,	0x7,	szCell_GateKeeperC	},
	{ICO_SkeletonA,		ICO_SkeletonA,		100,	65,	15,	30,	0x7,	szCell_SkeletonA	},
	{ICO_BigSlime,		ICO_BigSlime,		130,	60,	3,	8,	0x7,	szCell_BigSlime		},
	{ICO_BigBat,		ICO_BigBat,		60,	100,	8,	12,	0x7,	szCell_BigBat		},
	{ICO_Zombie,		ICO_Zombie,		260,	85,	5,	18,	0x7,	szCell_Zombie		},
	{ICO_SuperionPriest,	ICO_SuperionPriest,	100,	95,	30,	22,	0x7,	szCell_SuperionPriest	},
	{ICO_Rock,		ICO_Rock,		20,	100,	68,	28,	0x7,	szCell_Rock		},
	{ICO_ZombieKnight,	ICO_ZombieKnight,	320,	120,	15,	30,	0x7,	szCell_ZombieKnight	},
	{ICO_Vampire,		ICO_Vampire,		444,	199,	66,	144,	0x7,	szCell_Vampire		},
	{ICO_SlimeMan,		ICO_SlimeMan,		320,	140,	20,	30,	0x7,	szCell_SlimeMan		},
	{ICO_GhostSoldier,	ICO_GhostSoldier,	220,	180,	30,	35,	0x7,	szCell_GhostSoldier	},
	{ICO_Soldier,		ICO_Soldier,		210,	200,	65,	45,	0x7,	szCell_Soldier		},
	{ICO_GateKeeperB,	ICO_GateKeeperB,	100,	180,	110,	50,	0x7,	szCell_GateKeeperB	},
	{ICO_Swordsman,		ICO_Swordsman,		100,	680,	50,	55,	0x7,	szCell_Swordsman	},
	{ICO_Knight,		ICO_Knight,		160,	230,	105,	65,	0x7,	szCell_Knight		},
	{ICO_GoldenKnight,	ICO_GoldenKnight,	120,	150,	50,	100,	0x7,	szCell_GoldenKnight	},
	{ICO_SlimeLord,		ICO_SlimeLord,		360,	310,	20,	40,	0x7,	szCell_SlimeLord	},
	{ICO_VampireBat,	ICO_VampireBat,		200,	390,	90,	50,	0x7,	szCell_VampireBat	},
	{ICO_MagicianB,		ICO_MagicianB,		220,	370,	110,	80,	0x7,	szCell_MagicianB	},
	{ICO_MagicianA,		ICO_MagicianA,		200,	380,	130,	90,	0x7,	szCell_MagicianA	},
	{ICO_MagicSergeant,	ICO_MagicSergeant,	230,	450,	100,	100,	0x7,	szCell_MagicSergeant	},
	{ICO_DarkKnight,	ICO_DarkKnight,		180,	430,	210,	120,	0x7,	szCell_DarkKnight	},
	{ICO_GateKeeperA,	ICO_GateKeeperA,	180,	460,	360,	200,	0x7,	szCell_GateKeeperA	},
	{ICO_GiantOctopusNW,	ICO_GiantOctopusS,	1200,	180,	20,	50,	0x1,	szCell_GiantOctopus	},
	{ICO_GiantOctopusN,	ICO_GiantOctopusS,	1200,	180,	20,	50,	0x1,	szCell_GiantOctopus	},
	{ICO_GiantOctopusNE,	ICO_GiantOctopusS,	1200,	180,	20,	50,	0x1,	szCell_GiantOctopus	},
	{ICO_GiantOctopusW,	ICO_GiantOctopusS,	1200,	180,	20,	50,	0x1,	szCell_GiantOctopus	},
	{ICO_GiantOctopusC,	ICO_GiantOctopusS,	1200,	180,	20,	50,	0x1,	szCell_GiantOctopus	},
	{ICO_GiantOctopusE,	ICO_GiantOctopusS,	1200,	180,	20,	50,	0x1,	szCell_GiantOctopus	},
	{ICO_GiantOctopusSW,	ICO_GiantOctopusS,	1200,	180,	20,	50,	0x1,	szCell_GiantOctopus	},
	{ICO_GiantOctopusS,	ICO_GiantOctopusS,	1200,	180,	20,	100,	0x3,	szCell_GiantOctopus	},
	{ICO_GiantOctopusSE,	ICO_GiantOctopusS,	1200,	180,	20,	50,	0x1,	szCell_GiantOctopus	},
	{ICO_DragonNW,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_DragonN,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_DragonNE,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_DragonW,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_DragonC,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_DragonE,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_DragonSW,		ICO_Null,		0,	0,	0,	0,	0x8,	NULL			},
	{ICO_DragonS,		ICO_DragonS,		1500,	600,	250,	800,	0x3,	szCell_Dragon		},
	{ICO_DragonSE,		ICO_Null,		0,	0,	0,	0,	0x0,	NULL			},
	{ICO_GreatMagicMaster,	ICO_GreatMagicMaster,	4500,	560,	310,	1000,	0x3,	szCell_GreatMagicMaster	},
	{ICO_Zeno,		ICO_Zeno,		8000,	5000,	1000,	500,	0x3,	szCell_Zeno		},
	{ICO_Zeno,		ICO_Zeno,		800,	500,	100,	500,	0x3,	szCell_Zeno		},
	{ICO_Zeno,		ICO_Zeno,		1000,	625,	125,	500,	0x3,	szCell_Zeno		},
	{ICO_RedKey,		ICO_RedKeyP,		0,	0,	0,	0,	0x0,	szCell_RedKey		},
	{ICO_BlueKey,		ICO_BlueKeyP,		0,	0,	0,	0,	0x0,	szCell_BlueKey		},
	{ICO_YellowKey,		ICO_YellowKeyP,		0,	0,	0,	0,	0x0,	szCell_YellowKey	},
	{ICO_RedElixir,		ICO_RedElixirP,		50,	0,	0,	0,	0x0,	szCell_RedElixir	},
	{ICO_BlueElixir,	ICO_BlueElixirP,	200,	0,	0,	0,	0x0,	szCell_BlueElixir	},
	{ICO_RedCrystal,	ICO_RedCrystalP,	0,	1,	0,	0,	0x0,	szCell_RedCrystal	},
	{ICO_BlueCrystal,	ICO_BlueCrystalP,	0,	0,	1,	0,	0x0,	szCell_BlueCrystal	},
	{ICO_IronSword,		ICO_IronSwordP,		0,	10,	0,	0,	0x0,	szCell_IronSword	},
	{ICO_SilverSword,	ICO_SilverSwordP,	0,	20,	0,	0,	0x0,	szCell_SilverSword	},
	{ICO_SwordOfKnight,	ICO_SwordOfKnightP,	0,	40,	0,	0,	0x0,	szCell_SwordOfKnight	},
	{ICO_HolySword,		ICO_HolySwordP,		0,	50,	0,	0,	0x0,	szCell_HolySword	},
	{ICO_SacredSword,	ICO_SacredSwordP,	0,	100,	0,	0,	0x0,	szCell_SacredSword	},
	{ICO_IronShield,	ICO_IronShieldP,	0,	0,	10,	0,	0x0,	szCell_IronShield	},
	{ICO_SilverShield,	ICO_SilverShieldP,	0,	0,	20,	0,	0x0,	szCell_SilverShield	},
	{ICO_ShieldOfKnight,	ICO_ShieldOfKnightP,	0,	0,	40,	0,	0x0,	szCell_ShieldOfKnight	},
	{ICO_HolyShield,	ICO_HolyShieldP,	0,	0,	50,	0,	0x0,	szCell_HolyShield	},
	{ICO_SacredShield,	ICO_SacredShieldP,	0,	0,	100,	0,	0x0,	szCell_SacredShield	},
	{ICO_OrbOfHero,		ICO_OrbOfHeroP,		0,	0,	0,	0,	0x0,	szCell_OrbOfHero	},
	{ICO_OrbOfWisdom,	ICO_OrbOfWisdomP,	0,	0,	0,	0,	0x0,	szCell_OrbOfWisdom	},
	{ICO_OrbOfFlying,	ICO_OrbOfFlyingP,	0,	0,	0,	0,	0x0,	szCell_OrbOfFlying	},
	{ICO_Cross,		ICO_CrossP,		0,	0,	0,	0,	0x0,	szCell_Cross		},
	{ICO_MagicElixir,	ICO_MagicElixirP,	0,	0,	0,	0,	0x0,	szCell_MagicElixir	},
	{ICO_MagicMattock,	ICO_MagicMattockP,	0,	0,	0,	0,	0x0,	szCell_MagicMattock	},
	{ICO_DestructibleBall,	ICO_DestructibleBallP,	0,	0,	0,	0,	0x0,	szCell_DestructibleBall	},
	{ICO_WarpStaff,		ICO_WarpStaffP,		0,	0,	0,	0,	0x0,	szCell_WarpStaff	},
	{ICO_WingsToFlyUp,	ICO_WingsToFlyUpP,	0,	0,	0,	0,	0x0,	szCell_WingsToFlyUp	},
	{ICO_WingsToFlyDown,	ICO_WingsToFlyDownP,	0,	0,	0,	0,	0x0,	szCell_WingsToFlyDown	},
	{ICO_DragonSlayer,	ICO_DragonSlayerP,	0,	0,	0,	0,	0x0,	szCell_DragonSlayer	},
	{ICO_SnowCrystal,	ICO_SnowCrystalP,	0,	0,	0,	0,	0x0,	szCell_SnowCrystal	},
	{ICO_MagicKey,		ICO_MagicKeyP,		0,	0,	0,	0,	0x0,	szCell_MagicKey		},
	{ICO_SuperMagicMattock,	ICO_SuperMagicMattockP,	0,	0,	0,	0,	0x0,	szCell_SuperMagicMattock},
	{ICO_LuckyGold,		ICO_LuckyGoldP,		0,	0,	0,	0,	0x0,	szCell_LuckyGold	},
};
